name: Build

on: push

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Install optional build tools
        run: pip install pycodestyle pyflakes nose2
      - name: Check flakes
        run: pyflakes *.py
      - name: Check style
        run: pycodestyle *.py
      - name: Run unit tests
        run: nose2
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    needs: [checks]
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      - name: Install python deps
        run: pip install -r requirements.txt
      - name: Run visualization
        run: python draw_berkeley_bart.py berkeley_trips.csv berkeley_trips.png
      - name: Upload result
        uses: actions/upload-artifact@v4
        with:
          name: berkeley_trips
          path: berkeley_trips.png